# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Technology.create!([
  {name: "Ruby"},
  {name: "Ruby on Rails"},
  {name: "AngularJS"},
  {name: "SQL"},
  {name: "Sinatra"},
  {name: "PostgreSQL"},
  {name: "MySQL"},
  {name: "RSpec"},
  {name: "Capybara"},
  {name: "Jasmine"},
  {name: "Python"},
  {name: "MongoDB"},
  {name: "Node.js"},
  {name: "Express"},
  {name: "Backbone.js"},
  {name: "Foundation"},
  {name: "Java"},
  {name: "React"},
  {name: "PHP"},
  {name: "Firebase"},
  {name: "C++"},
  {name: "Sass"},
  {name: "D3.js"},
  {name: "Handlebars"},
  {name: "Meteor"},
  {name: "Photoshop"},
  {name: "Ionic"},
  {name: "Django"},
  {name: "Swift"},
  {name: "C"},
  {name: "Selenium"},
  {name: "Ember.js"},
  {name: "C#"},
  {name: ".Net"},
  {name: "R"},
  {name: "Mongoose"},
  {name: "MATLAB"},
  {name: "Drupal"},
  {name: "PhoneGap"},
  {name: "Cordova"},
  {name: "Flask"},
  {name: "Cucumber"},
  {name: "Perl"},
  {name: "ASP.net"},
  {name: "iOS"},
  {name: "Android"},
  {name: "Go"},
  {name: "Elixir"},
  {name: "Erlang"},
  {name: "Rust"},
  {name: "Scala"},
  {name: "Clojure"},
  {name: "CouchDB"},
  {name: "Hadoop"},
  {name: "Hive"},
  {name: "Spark"},
  {name: "Language Agnostic"},
  {name: "Objective-C"},
  {name: "CoffeeScript"},
  {name: "JavaScript"},
  {name: "HTML"},
  {name: "CSS"},
  {name: "Git"}
])